# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
"""Tests for the CartridgeKRIProvider — the first production provider.

These tests use real ``.pt`` files generated by the cherry-picked
``scripts/generate_kmeans_prior.py``.  Two priors live in
``/data/knlp-key-results/routing-w7900-kri-20260406/`` from the Goal 1
W7900 validation work:

* ``routing_prior_kmeans.pt`` — legacy single-cluster prior
  (only ``kmeans_blocks``, no per-K dict).  Exercises the legacy
  fallback in ``BlockManifest.from_kri_prior``.
* ``routing_prior_kmeans_perK.pt`` — per-K prior generated with
  ``--per-k 4,8,16,32``.  Exercises the principled per-K dispatch.

The two files were generated from the same citation-check cartridge but
with different generator flags, so the *block selections* differ at
small K — the per-K K=4 selection is full-document
``[10, 102, 174, 242]`` while a naive truncation of the legacy
32-cluster list gives the low-index-biased ``[10, 14, 24, 31]``.  This
divergence is the dispatch bug the routing brief warned about, and the
tests below assert it explicitly so any future regression to the
truncation path fails loudly.

Tests are skipped if the prior files are not present (so CI without
the W7900 results bundle doesn't fail), but they run on prune where
the artifacts live.
"""
from __future__ import annotations

from pathlib import Path

import pytest
import torch  # noqa: F401  — imported so the skip happens before

from vllm.v1.core.spf.config import SPFConfig
from vllm.v1.core.spf.controller import SPFController
from vllm.v1.core.spf.providers import CartridgeKRIProvider

# CartridgeKRIProvider is instantiated, surfacing missing
# torch as an import error rather than a runtime crash

GOAL1_DIR = Path("/data/knlp-key-results/routing-w7900-kri-20260406")
LEGACY_PRIOR = GOAL1_DIR / "routing_prior_kmeans.pt"
PERK_PRIOR = GOAL1_DIR / "routing_prior_kmeans_perK.pt"


def _require(path: Path) -> Path:
    if not path.exists():
        pytest.skip(f"Prior fixture not present: {path}")
    return path


# ---------------------------------------------------------------------------
# Provider registration tests
# ---------------------------------------------------------------------------


class TestCartridgeKRIProviderRegistration:

    def test_register_legacy_prior(self) -> None:
        path = _require(LEGACY_PRIOR)
        provider = CartridgeKRIProvider()
        entry = provider.register_prior(
            prefix_hash="abc123",
            prior_path=path,
            prior_type="kri_g",
        )
        assert entry.prefix_hash == "abc123"
        assert entry.prior_type == "kri_g"
        assert "kmeans_blocks" in entry.prior
        assert "kmeans_blocks_perK" not in entry.prior
        assert provider.stats()["num_priors"] == 1

    def test_register_perk_prior(self) -> None:
        path = _require(PERK_PRIOR)
        provider = CartridgeKRIProvider()
        entry = provider.register_prior(
            prefix_hash="abc123",
            prior_path=path,
            prior_type="kri_g",
        )
        assert "kmeans_blocks_perK" in entry.prior
        assert sorted(
            entry.prior["kmeans_blocks_perK"].keys()) == [4, 8, 16, 32]

    def test_register_rejects_non_dict(self, tmp_path) -> None:
        bad = tmp_path / "bad.pt"
        torch.save([1, 2, 3], bad)
        provider = CartridgeKRIProvider()
        with pytest.raises(ValueError, match="not a dict"):
            provider.register_prior(prefix_hash="x", prior_path=bad)

    def test_register_rejects_empty_prior(self, tmp_path) -> None:
        bad = tmp_path / "empty.pt"
        torch.save({"version": 1}, bad)
        provider = CartridgeKRIProvider()
        with pytest.raises(ValueError, match="kmeans"):
            provider.register_prior(prefix_hash="x", prior_path=bad)


# ---------------------------------------------------------------------------
# Manifest lookup — the dispatch path that proves the cherry-pick works
# ---------------------------------------------------------------------------


class TestCartridgeKRIManifestLookup:

    def test_legacy_prior_returns_truncated_manifest(self) -> None:
        path = _require(LEGACY_PRIOR)
        provider = CartridgeKRIProvider()
        provider.register_prior(prefix_hash="abc123", prior_path=path)

        m = provider.get_manifest(
            prefix_hash="abc123",
            query_hash=None,
            K=4,
        )
        assert m is not None
        assert m.K == 4
        # Legacy fallback uses sorted(kmeans_blocks)[:K] — low-index
        # biased, this is the known dispatch bug regime.
        assert list(m.block_indices) == [10, 14, 24, 31]
        assert m.total_blocks == 258
        assert m.savings_blocks == 254
        assert m.prior_type == "kri_g"

    def test_perk_prior_returns_principled_manifest(self) -> None:
        path = _require(PERK_PRIOR)
        provider = CartridgeKRIProvider()
        provider.register_prior(prefix_hash="abc123", prior_path=path)

        m = provider.get_manifest(
            prefix_hash="abc123",
            query_hash=None,
            K=4,
        )
        assert m is not None
        assert m.K == 4
        # Per-K K=4 is full-document, NOT truncation of the K=32 list.
        # This is the property the routing-side per-K dispatch fix
        # (commit 3b2a58934) guarantees and that we're verifying the
        # SPF-side parser respects.
        assert list(m.block_indices) == [10, 102, 174, 242]
        assert m.block_indices != (10, 14, 24, 31)  # not truncation
        assert m.total_blocks == 258

    def test_perk_dispatch_at_k8(self) -> None:
        path = _require(PERK_PRIOR)
        provider = CartridgeKRIProvider()
        provider.register_prior(prefix_hash="abc123", prior_path=path)

        m = provider.get_manifest(
            prefix_hash="abc123",
            query_hash=None,
            K=8,
        )
        assert m is not None
        assert m.K == 8
        # K=8 is the validated KRI regime — distinct from legacy K=8.
        assert list(m.block_indices) == [10, 57, 77, 102, 159, 174, 221, 246]

    def test_unknown_prefix_returns_none(self) -> None:
        path = _require(PERK_PRIOR)
        provider = CartridgeKRIProvider()
        provider.register_prior(prefix_hash="abc123", prior_path=path)
        assert provider.get_manifest(
            prefix_hash="DOES_NOT_EXIST",
            query_hash=None,
            K=8,
        ) is None

    def test_query_hash_falls_back_to_query_agnostic(self) -> None:
        """KRI-G providers serve KRI-Q-keyed lookups via fallback."""
        path = _require(PERK_PRIOR)
        provider = CartridgeKRIProvider()
        provider.register_prior(prefix_hash="abc123", prior_path=path)
        # No KRI-Q prior was registered for this query, but the
        # KRI-G prior should still answer.
        m = provider.get_manifest(
            prefix_hash="abc123",
            query_hash="qwarranty",
            K=8,
        )
        assert m is not None
        assert m.K == 8

    def test_query_specific_prior_takes_precedence(self) -> None:
        """If both KRI-Q and KRI-G priors exist for the same prefix,
        an exact ``(prefix_hash, query_hash)`` lookup takes precedence."""
        kg_path = _require(PERK_PRIOR)
        kq_path = _require(LEGACY_PRIOR)  # different selections
        provider = CartridgeKRIProvider()
        # KRI-G query-agnostic
        provider.register_prior(
            prefix_hash="abc123",
            prior_path=kg_path,
            prior_type="kri_g",
        )
        # KRI-Q query-specific (legacy file used as a stand-in source)
        provider.register_prior(
            prefix_hash="abc123",
            prior_path=kq_path,
            prior_type="kri_q",
            query_hash="qwarranty",
        )

        # Query-specific lookup -> KRI-Q
        mq = provider.get_manifest(
            prefix_hash="abc123",
            query_hash="qwarranty",
            K=4,
        )
        assert mq is not None
        assert mq.prior_type == "kri_q"
        # Legacy prior at K=4 -> [10, 14, 24, 31]
        assert list(mq.block_indices) == [10, 14, 24, 31]

        # Query-agnostic lookup -> KRI-G (per-K, principled)
        mg = provider.get_manifest(
            prefix_hash="abc123",
            query_hash=None,
            K=4,
        )
        assert mg is not None
        assert mg.prior_type == "kri_g"
        assert list(mg.block_indices) == [10, 102, 174, 242]


# ---------------------------------------------------------------------------
# Controller integration with the real provider
# ---------------------------------------------------------------------------


class TestCartridgeKRIProviderInController:

    def test_controller_emits_perk_bounded_hints(self) -> None:
        path = _require(PERK_PRIOR)
        provider = CartridgeKRIProvider()
        provider.register_prior(prefix_hash="abc123", prior_path=path)

        config = SPFConfig(
            enabled=True,
            scorer="session_aware",
            max_prefetch_blocks=1024,
            prefetch_fraction=1.0,
            lookahead_steps=4,
            metrics_interval=10_000,
            target_K=8,
        )
        controller = SPFController(config, manifest_provider=provider)
        controller.observe_request(session_id="s1", prefix_hash="abc123")
        hints = controller.step(
            free_gpu_blocks=1024,
            resident_prefixes={"abc123"},
        )
        assert len(hints) == 1
        m = hints[0].manifest
        assert m is not None
        assert m.K == 8
        assert m.total_blocks == 258
        assert m.savings_blocks == 250
        # Confirm the principled per-K block list is in the hint —
        # this is the cherry-picked dispatch fix flowing end-to-end
        # through the SPF controller.
        assert list(m.block_indices) == [10, 57, 77, 102, 159, 174, 221, 246]

    def test_controller_falls_back_when_no_prior_registered(self) -> None:
        provider = CartridgeKRIProvider()
        # No registration → all lookups miss.
        config = SPFConfig(
            enabled=True,
            scorer="session_aware",
            max_prefetch_blocks=64,
            prefetch_fraction=1.0,
            lookahead_steps=4,
            metrics_interval=10_000,
            target_K=8,
        )
        controller = SPFController(config, manifest_provider=provider)
        controller.observe_request(session_id="s1", prefix_hash="xyz")
        hints = controller.step(
            free_gpu_blocks=1024,
            resident_prefixes={"xyz"},
        )
        # Hint emitted via legacy unbounded path.
        assert len(hints) == 1
        assert hints[0].manifest is None


# ---------------------------------------------------------------------------
# Stats / introspection
# ---------------------------------------------------------------------------


class TestProviderStats:

    def test_stats_after_registration(self) -> None:
        path = _require(PERK_PRIOR)
        provider = CartridgeKRIProvider()
        provider.register_prior(prefix_hash="abc123", prior_path=path)
        provider.register_prior(
            prefix_hash="def456",
            prior_path=path,
            prior_type="kri_g",
        )
        stats = provider.stats()
        assert stats["num_priors"] == 2
        assert sorted(stats["prefix_hashes"]) == ["abc123", "def456"]
        assert stats["prior_types"] == ["kri_g"]
