# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
"""Concrete BlockManifestProvider implementations.

Today the only production-ready provider is :class:`CartridgeKRIProvider`,
which reads ``routing_prior_kmeans*.pt`` priors generated by the routing
team's ``scripts/generate_kmeans_prior.py --per-k`` flow.  Future
KRI-x variants and RAG-KRI providers will land here as siblings.
"""
from vllm.v1.core.spf.providers.cartridge_kri import CartridgeKRIProvider

__all__ = ["CartridgeKRIProvider"]
